---
# tasks file for letsencrypt-certbot

- name: Add Certbot repository key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 75BCA694
 
- name: Add Certbot repository
  become: true
  apt_repository:
    repo: ppa:certbot/certbot
    state: present

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install Certbot apt package
  become: true
  apt:
    name: certbot
    state: present

- name: Install ssl-cert
  become: true
  apt:
    name: ssl-cert
    state: present

- name: Issue certificate
  become: true
  shell: certbot certonly -n --agree-tos --rsa-key-size 4096 --email "{{ letsencrypt.email }}" --standalone --preferred-challenges http -d "{{ letsencrypt.domain }}" --pre-hook "chmod 750 /etc/letsencrypt; ufw allow 80" --post-hook "ufw delete allow 80; chgrp -R ssl-cert /etc/letsencrypt; find /etc/letsencrypt -name 'privkey*.pem' -exec chmod 440 {} \;"

- name: Enable renewals
  become: true
  shell: certbot renew --pre-hook "chmod 750 /etc/letsencrypt; ufw allow 80" --post-hook "ufw delete allow 80; chgrp -R ssl-cert /etc/letsencrypt; find /etc/letsencrypt -name 'privkey*.pem' -exec chmod 440 {} \;"
